---
title: "Cofit x Genensis"
subtitle: " 醫療大數據 (分析報告)"
author: "MA-DS TEAM"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    dev: svglite
    css: css/style.css
    split_by: section
    config:
      toc:
        collapse: none
      download: null
      edit: null
      sharing: null
      search: yes
    

  bookdown::html_chapters:
    css: [css/style.css, css/toc.css]

  bookdown::pdf_book:
    pandoc_args: --top-level-division=chapter
    toc_depth: 3
    toc_unnumbered: no
    toc_appendix: yes
    quote_footer: ["\\VA{", "}{}"]
  bookdown::epub_book:
    dev: svglite
    stylesheet: css/style.css
---

```{r setup, include=FALSE}
library(googleVis)
knitr::opts_chunk$set(echo = FALSE, comment = NA, results = 'asis', warning = FALSE)
options(knitr.graphics.auto_pdf = TRUE, gvis.plot.tag = 'chart')

```

# Preface {#index .unnumbered}

![[Page Example]cover:](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/1200px-Wikipedia-logo-v2.svg.png){width="219"}

**Last updated on: `r format (Sys.Date(), '%d %b %Y')`**.

Introduction context...(editing)

#### Disclaimer {.unnumbered}

The information in this book is provided ...(editing).

```{r}
Sys.time()
```
